// For my windows machine
global root "C:\Users\CHENY\Documents\GitHub\term_paper"
global data "$root\data"
global raw "$data\raw_data"
global processed "$data\processed_data"
global final "$data\final_data"
global results "$root\results"
global eda "$results\eda"
global analysis "$results\analysis"
global robustness "$results\robustness"